### ISSUE TITLE
Errors when compiling in Visual Studio

### ISSUE THREAD

**Issue by egg-mayo-sandwich** [aaaddress1/Skrull#1]
Hi, I'm compiling the source code in Visual Studio Community 2019 but am getting the following errors:

![image](https://user-images.githubusercontent.com/62365248/138017541-0fdd320d-5703-42c3-af0c-0dacdb344805.png)

What I'm doing is launch Visual Studio 2019 > Open a project or solution > Skrull.vcxproj.

Please let me know if there is a way to resolve this or an alternative way of compiling. Thank you.

**Comment by aaaddress1** [comment]
please compile it in 64-bit mode. you can see the error detail, that x64 definition `__readgsqword()` is missing. 
only `__readfsqword()` existing on 32-bit mode.

**Comment by egg-mayo-sandwich** [comment]
I see, I've compiled in 64-bit and it works. Thank you so much!
